<?php

namespace Database\Seeders;

use App\Models\Task;
use App\Models\TaskCategory;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class TaskSeeder extends Seeder
{
    public function run(): void
    {
        $cat = fn($slug) => TaskCategory::whereSlug($slug)->first()?->id;

        $tasks = [
            [
                'category_id' => $cat('social-media'),
                'title' => 'Like our Facebook Page',
                'slug' => 'like-facebook-page',
                'description' => 'Visit our Facebook page and hit the Like button. Take a screenshot as proof.',
                'instructions' => '1. Click the link below\n2. Like our Facebook page\n3. Upload a screenshot as proof',
                'task_type' => 'social_media',
                'reward' => 2.00,
                'total_slots' => 500,
                'remaining_slots' => 500,
                'external_link' => 'https://facebook.com/earnbirr',
                'proof_type' => '["screenshot"]',
                'end_date' => Carbon::now()->addDays(30),
                'status' => 1,
            ],
            [
                'category_id' => $cat('social-media'),
                'title' => 'Follow on Twitter/X',
                'slug' => 'follow-twitter',
                'description' => 'Follow our Twitter/X account and earn rewards.',
                'instructions' => '1. Click the link\n2. Follow the account\n3. Submit your Twitter username as proof',
                'task_type' => 'social_media',
                'reward' => 1.50,
                'total_slots' => 300,
                'remaining_slots' => 300,
                'external_link' => 'https://twitter.com/earnbirr',
                'proof_type' => '["text"]',
                'end_date' => Carbon::now()->addDays(30),
                'status' => 1,
            ],
            [
                'category_id' => $cat('social-media'),
                'title' => 'Subscribe to YouTube Channel',
                'slug' => 'subscribe-youtube',
                'description' => 'Subscribe to our YouTube channel and earn rewards.',
                'instructions' => '1. Click the link\n2. Subscribe to the channel\n3. Screenshot your subscription as proof',
                'task_type' => 'social_media',
                'reward' => 3.00,
                'total_slots' => 200,
                'remaining_slots' => 200,
                'external_link' => 'https://youtube.com/@earnbirr',
                'proof_type' => '["screenshot"]',
                'end_date' => Carbon::now()->addDays(45),
                'status' => 1,
            ],
            [
                'category_id' => $cat('micro-tasks'),
                'title' => 'Data Entry - Product Listings',
                'slug' => 'data-entry-products',
                'description' => 'Help us populate product listings. Enter product names, descriptions, and prices from provided images.',
                'instructions' => '1. Read the instructions document\n2. Enter data for 10 products\n3. Submit the completed spreadsheet',
                'task_type' => 'micro_task',
                'reward' => 5.00,
                'total_slots' => 100,
                'remaining_slots' => 100,
                'proof_type' => '["file"]',
                'end_date' => Carbon::now()->addDays(60),
                'status' => 1,
            ],
            [
                'category_id' => $cat('micro-tasks'),
                'title' => 'Image Tagging - Product Photos',
                'slug' => 'image-tagging',
                'description' => 'Tag product images with relevant keywords to improve search functionality.',
                'instructions' => '1. View each image\n2. Add 5-10 relevant tags per image\n3. Submit tags in the required format',
                'task_type' => 'micro_task',
                'reward' => 2.50,
                'total_slots' => 200,
                'remaining_slots' => 200,
                'proof_type' => '["text","file"]',
                'end_date' => Carbon::now()->addDays(30),
                'status' => 1,
            ],
            [
                'category_id' => $cat('micro-tasks'),
                'title' => 'Verify Website Links',
                'slug' => 'verify-links',
                'description' => 'Check a list of website URLs and verify they are working. Report broken links.',
                'instructions' => '1. Open each URL\n2. Check if the page loads correctly\n3. Mark working/broken in the spreadsheet',
                'task_type' => 'micro_task',
                'reward' => 1.00,
                'total_slots' => 500,
                'remaining_slots' => 500,
                'proof_type' => '["file"]',
                'end_date' => Carbon::now()->addDays(15),
                'status' => 1,
            ],
            [
                'category_id' => $cat('surveys'),
                'title' => 'Market Research Survey 2026',
                'slug' => 'market-research-survey',
                'description' => 'Participate in our market research survey about online earning preferences in Ethiopia.',
                'instructions' => '1. Click the survey link\n2. Answer all questions honestly\n3. Submit the completed survey',
                'task_type' => 'survey',
                'reward' => 10.00,
                'total_slots' => 50,
                'remaining_slots' => 50,
                'external_link' => 'https://survey.earnbirr.com/market2026',
                'proof_type' => '["link"]',
                'end_date' => Carbon::now()->addDays(14),
                'status' => 1,
            ],
            [
                'category_id' => $cat('surveys'),
                'title' => 'Customer Satisfaction Survey',
                'slug' => 'customer-satisfaction',
                'description' => 'Help us improve by completing a short survey about your experience.',
                'instructions' => '1. Click the survey link\n2. Rate your experience\n3. Provide feedback',
                'task_type' => 'survey',
                'reward' => 5.00,
                'total_slots' => 100,
                'remaining_slots' => 100,
                'external_link' => 'https://survey.earnbirr.com/feedback',
                'proof_type' => '["link"]',
                'end_date' => Carbon::now()->addDays(21),
                'status' => 1,
            ],
            [
                'category_id' => $cat('freelance'),
                'title' => 'Logo Design - Small Business',
                'slug' => 'logo-design',
                'description' => 'Design a professional logo for a small business. Requirements provided in the instructions.',
                'instructions' => '1. Read the brief\n2. Design the logo\n3. Submit as PNG/SVG file',
                'task_type' => 'freelance',
                'reward' => 150.00,
                'total_slots' => 5,
                'remaining_slots' => 5,
                'proof_type' => '["file"]',
                'end_date' => Carbon::now()->addDays(14),
                'status' => 1,
            ],
            [
                'category_id' => $cat('freelance'),
                'title' => 'Content Writing - Blog Posts',
                'slug' => 'content-writing',
                'description' => 'Write a 500-word blog post on "How to Earn Money Online in Ethiopia".',
                'instructions' => '1. Research the topic\n2. Write a 500-word article\n3. Submit as a Word document',
                'task_type' => 'freelance',
                'reward' => 80.00,
                'total_slots' => 10,
                'remaining_slots' => 10,
                'proof_type' => '["file"]',
                'end_date' => Carbon::now()->addDays(10),
                'status' => 1,
            ],
            [
                'category_id' => $cat('freelance'),
                'title' => 'Amharic to English Translation',
                'slug' => 'amharic-translation',
                'description' => 'Translate 1000 words from Amharic to English. Document provided.',
                'instructions' => '1. Download the source document\n2. Translate accurately\n3. Submit both original and translation',
                'task_type' => 'freelance',
                'reward' => 200.00,
                'total_slots' => 3,
                'remaining_slots' => 3,
                'proof_type' => '["file"]',
                'end_date' => Carbon::now()->addDays(7),
                'status' => 1,
            ],
        ];

        foreach ($tasks as $task) {
            Task::updateOrCreate(['slug' => $task['slug']], $task);
        }
    }
}
